<a href="https://colab.research.google.com/github/vicksCoghi/data_Manual/blob/main/Atv1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
lista = list(range(0,16,1)) #criando lista de 0 até 15

In [9]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [11]:
my_array = np.array(lista) #convertendo lista para array

In [12]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
array_np = np.arange(0,16,1) #criando array direto com Numpy
array_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
array_zeros = np.zeros(11, dtype = int)
array_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
array_cinco = np.full(10, 5)
array_cinco

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [27]:
array2 = np.arange(10,51,1)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [29]:
matriz_identidade = np.identity(3) #criando matriz identidade
matriz_identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
matriz_identidade2 = np.eye(3) #outra forma de matriz identidade
matriz_identidade2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])