<a href="https://colab.research.google.com/github/vicksCoghi/data_Manual/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
lista = [0,1,2,3,4,5,6,7,8]
lista


[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
myArray = np.array(lista)
myArray
print(myArray)

[0 1 2 3 4 5 6 7 8]


In [ ]:
lista = list(range(9))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array3 = np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [ ]:
array3 = np.arange(0,10,0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
type(array4)

numpy.ndarray

In [ ]:
print(array4.dtype)

float64


In [ ]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


In [ ]:
vetor1[3]

3

In [ ]:
vetor1[0:2]

array([0, 1])

In [ ]:
print(vetor1[0:3])

[0 1 2]


In [ ]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
vetor1[0] = "gato"
vetor1

In [ ]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

In [ ]:
matriz1 = np.array([[0,1,2],
                    [3,4,5]])
print(matriz1)

matriz2 = np.array([[7,8,9],[6,8,5]])
print(matriz2)

[[0 1 2]
 [3 4 5]]
[[7 8 9]
 [6 8 5]]


In [ ]:
minhaLista = [[21,10,8],[81,20,15],[15,26,47]]
minhaMatriz = np.matrix(minhaLista)
print(minhaMatriz)

[[21 10  8]
 [81 20 15]
 [15 26 47]]


In [ ]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [ ]:
x = np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x = np.ones((4,4)) * 8
x


array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [ ]:
z = np.diag(np.array([1,2,3,4,5,6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
y = np.eye(5, dtype=int)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
np.shape(z)
z.shape

(6, 6)

In [ ]:
minhaMatriz[2,1]

26

In [ ]:
print(minhaMatriz[0,:])

[[21 10  8]]


In [ ]:
print(minhaMatriz[:,2])

[[ 8]
 [15]
 [47]]


In [ ]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 21,  10,   8],
        [100,  20,  15],
        [ 15,  26,  47]])

In [ ]:
np.sum(myArray)


36

In [ ]:
np.prod(myArray)
myArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.cumsum(myArray)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
myArray.min()

0

In [ ]:
myArray.max()

8

In [ ]:
np.mean(myArray)

4.0

In [ ]:
np.median(myArray)

4.0

In [ ]:
np.var(myArray)

6.666666666666667

In [ ]:
np.std(myArray)

2.581988897471611

In [ ]:
newArray=np.arange(20)
newArray[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
newArray[1:19:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
np.mean(newArray)

9.5

In [ ]:
np.median(newArray)

9.5

In [ ]:
np.prod(newArray)

0

In [ ]:
np.sum(newArray)

190

In [ ]:
np.var(newArray)

33.25

In [ ]:
np.std(newArray)

5.766281297335398

In [ ]:
myArray>5

array([False, False, False, False, False, False,  True,  True,  True])

In [ ]:
myArray[myArray>5]

array([6, 7, 8])